Debugged genUser file; TODO: Debug usermod commands

diff --git a/genUser b/genUser
--- a/genUser
+++ b/genUser
@@ -1,7 +1,6 @@
 #!/bin/bash
-#sudo bash #To force run the script as superUser
+#TODO: Need to trap on successful completion
 #trap "echo '\\n'All the users were created successfully." EXIT
-echo `readlink $0`
 
 #Only consider the first paramater if many are given -- $1
 if [ -n "$1" ] && [ -f "$1" ]; then
@@ -27,46 +26,55 @@ fi
 SERVER_DIR=/home/OmegaServer
 MANAGER_FILES=managerHome
 USER_FILES=userHome
+LOGFILE=log_files/info.log
 
-mkdir log_files
+mkdir -p log_files
+echo "" > $LOGFILE # Initialize log file for current run
 mkdir -p $SERVER_DIR
 #Create userlevel groups
 for x in Users Managers Ceo;do
-	echo "groupadd omega"$x
+	groupadd omega$x 2>/dev/null # To throw duplicate addition error
 done
 
 cat  $userAccounts | while read aNum branch citizen age legacy; do
 #	Create Branch
 	if ! ( id $branch &> /dev/null); then
-		echo "useradd -g omegaManagers -G omegaUsers -mk $MANAGER_FILES -b $SERVER_DIR $branch"
+##	Note: Branch Balance and Transaction history are initiated by updateBranch script
+		useradd -g omegaManagers -G omegaUsers -mk $MANAGER_FILES -b $SERVER_DIR $branch
 		echo $branch >> log_files/managers.log # Or Branches
+		echo "Created Branch: $branch" | tee -a $LOGFILE # Pipe can be replaced with redirection to supress output to /dev/stdout
 	fi
 #	Create Account
 	if ! ( id $aNum &> /dev/null);then
-		echo "useradd -g omegaUsers -mk $USER_FILES -b $SERVER_DIR/$branch $aNum"
-		echo $aNum>>log_files/users.log
+		(useradd -g omegaUsers -mk $USER_FILES -b $SERVER_DIR/$branch $aNum || (echo "user $aNum not created" && continue))
+		echo $aNum>>log_files/users.log #These files can be used to remove the users and groups
 	else
-		echo "User $aNum already exists"
+		echo "User $aNum already exists" | tee -a $LOGFILE
+		continue
 	fi
 #	Create a group based on citizenship
-	if ! ( id $citizen &> /dev/null); then #Assuming the citizenship as the required category
-		echo "groupadd $citizen"
+	if ! ( getent group $citizen &> /dev/null); then #Assuming the citizenship as the required category
+		groupadd $citizen
 		echo $citizen >> log_files/citizenship.log
+		echo "Created Citizenship: $citizen" | tee -a $LOGFILE
 	fi
-#	Create a group based on age reservation
+#	Create a group based on age reservation OPTIONAL
 	if [ $age = "-" ]; then
 		age=""
-	elif ! ( id $age &> /dev/null ); then
-		echo "groupadd $age"
+	elif ! ( getent group $age &> /dev/null ); then
+		groupadd $age
 		echo $age >> log_files/age_reservation.log
+		echo "Created Age reservation: $age" | tee -a $LOGFILE
 	fi
-#	Create a group based on legacy
+#	Create a group based on legacy OPTIONAL
 	if [ $legacy = "-" ]; then
 		legacy=""
-	elif ! ( id $legacy &> /dev/null ); then
-		echo "groupadd $legacy"
+	elif ! ( getenet group $legacy &> /dev/null ); then
+		groupadd $legacy
 		echo $legacy >> log_files/legacy.log
+		echo "Created legacy category: $legacy" | tee -a $LOGFILE
 	fi
 #	Add the user to the respective groups
-	echo "usermod -aG $citizen $age $legacy"
+	usermod -aG $citizen $age $legacy $aNum
+	echo "Created user: $aNum" | tee -a $LOGFILE
 done
